databaseChangeLog:
  - changeSet:
      id: 1
      author: JakubPavlicek
      changes:
        - createTable:
            tableName: production_company
            columns:
              - column:
                  name: id
                  type: varchar(255)
                  defaultValueComputed: uuid_generate_v4()
                  constraints:
                    primaryKey: true
                    nullable: false
                    unique: true
              - column:
                  name: name
                  type: varchar(100)
                  constraints:
                    nullable: false
                    unique: true