FROM maven:3.9.9-eclipse-temurin-23-alpine AS build
WORKDIR /app
COPY /api/pom.xml .
RUN mvn dependency:go-offline
COPY /api/src ./src
COPY openapi.yaml ./src/main/resources/static
RUN mvn clean package -DskipTests

FROM eclipse-temurin:23-jre AS production
WORKDIR /app
COPY --from=build /app/target/*.jar MovieManager.jar
EXPOSE 8080
RUN groupadd spring && \
    useradd -g spring kuba
USER kuba
ENTRYPOINT ["java", "-Duser.timezone=Europe/Prague", "-jar", "MovieManager.jar"]