spring:
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-root.yaml