spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-root.yaml
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    url: openapi.yaml