openapi: 3.1.0
info:
  title: Movie Manager
  description: A movie manager API.
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /movies:
    get:
      description: 'Returns all movies'
