openapi: 3.0.0
info:
  title: Movie Manager
  description: A movie manager API.
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Local server

components:

  parameters:

    movieId:
      name: movieId
      in: path
      schema:
        type: string
      required: true
      description: The movie ID.
    page:
      name: page
      in: query
      description: The page number for pagination.
      schema:
        type: integer
        format: int32
        default: 0
        minimum: 0
    limit:
      name: limit
      in: query
      description: The maximum number of items to return per page.
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 10
    sort:
      name: sort
      in: query
      description: |
        A comma-separated list of sort keys.
        Valid keys are 'name', 'release', 'length', 'description', 'director'.
        Each key can be sorted by either: asc (ascending order) or desc (descending order).
        Example usage: ?sort=name.desc,length.asc.
      schema:
        type: string
        default: "name.asc"
        maxLength: 200
    name:
      name: name
      in: query
      schema:
        type: string
        default: "eq:"
        example: "eq:The Conjuring"
        maxLength: 200
    release:
      name: release
      in: query
      schema:
        type: string
        default: "eq:"
        example: "eq:2024-07-29"
        maxLength: 100
    length:
      name: length
      in: query
      schema:
        type: string
        default: "gte:0"
        example: "gte:100"
        maxLength: 100
    description:
      name: description
      in: query
      schema:
        type: string
        default: "like:"
        example: "like:The"
        maxLength: 1100
    director:
      name: director
      in: query
      schema:
        type: string
        default: "eq:"
        example: "eq:James Wan"
        maxLength: 100
    actors:
      name: actor
      in: query
      schema:
        type: array
        default: [ "eq:" ]
        items:
          type: string
          example: "eq:James Wan"
          maxLength: 100
    genres:
      name: genre
      in: query
      schema:
        type: array
        default: [ "eq:" ]
        items:
          type: string
          example: "eq:Horror"
          maxLength: 100
    countries:
      name: country
      in: query
      schema:
        type: array
        default: [ "eq:" ]
        items:
          type: string
          example: "eq:South Korea"
          maxLength: 100

  schemas:

    MovieName:
      type: string
      example: The Conjuring
      minLength: 1
      maxLength: 100
      nullable: false
    MovieRelease:
      type: string
      format: date
      example: 2024-07-29
      nullable: false
    MovieLength:
      type: integer
      format: int32
      example: 112
      minimum: 1
      nullable: false
    MovieDescription:
      type: string
      example: Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.
      minLength: 1
      maxLength: 1000
      nullable: false

    MovieResponse:
      type: object
      properties:
        movieId:
          type: string
          example: 872e1723-09ac-461d-9f54-d4c221269bed
        name:
          $ref: '#/components/schemas/MovieName'
        release:
          $ref: '#/components/schemas/MovieRelease'
        length:
          $ref: '#/components/schemas/MovieLength'
        description:
          $ref: '#/components/schemas/MovieDescription'
        director:
          $ref: '#/components/schemas/DirectorDTO'
        actors:
          type: array
          items:
            $ref: '#/components/schemas/ActorDTO'
        genres:
          type: array
          items:
            $ref: '#/components/schemas/GenreDTO'
        countries:
          type: array
          items:
            $ref: '#/components/schemas/CountryDTO'

    DirectorDTO:
      type: object
      properties:
        name:
          type: string
          example: James Wan
          minLength: 1
          maxLength: 50
          nullable: false

    ActorDTO:
      type: object
      properties:
        name:
          type: string
          example: Patrick Wilson
          minLength: 1
          maxLength: 50
          nullable: false

    GenreDTO:
      type: object
      properties:
        name:
          type: string
          enum:
            - Action
            - Adventure
            - Animation
            - Biography
            - Comedy
            - Crime
            - Documentary
            - Drama
            - Family
            - Fantasy
            - Film-Noir
            - History
            - Horror
            - Music
            - Musical
            - Mystery
            - Romance
            - Sci-Fi
            - Sport
            - Superhero
            - Thriller
            - War
            - Western
          example: Horror

    CountryDTO:
      type: object
      properties:
        name:
          type: string
          enum:
            - United States
            - Canada
            - United Kingdom
            - Australia
            - Germany
            - France
            - Italy
            - Spain
            - Japan
            - China
            - India
            - Brazil
            - Russia
            - Mexico
            - South Korea
            - South Africa
            - Netherlands
            - Sweden
            - Norway
            - Denmark
            - Finland
            - New Zealand
            - Argentina
            - Belgium
            - Switzerland
          example: Italy
          nullable: false

    AddMovieRequest:
      type: object
      required:
        - name
        - release
        - length
        - description
        - actors
        - genres
        - countries
      properties:
        name:
          $ref: '#/components/schemas/MovieName'
        release:
          $ref: '#/components/schemas/MovieRelease'
        length:
          $ref: '#/components/schemas/MovieLength'
        description:
          $ref: '#/components/schemas/MovieDescription'
        director:
          $ref: '#/components/schemas/DirectorDTO'
        actors:
          type: array
          items:
            $ref: '#/components/schemas/ActorDTO'
        genres:
          type: array
          items:
            $ref: '#/components/schemas/GenreDTO'
        countries:
          type: array
          items:
            $ref: '#/components/schemas/CountryDTO'

    UpdateMovieRequest:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/MovieName'
        release:
          $ref: '#/components/schemas/MovieRelease'
        length:
          $ref: '#/components/schemas/MovieLength'
        description:
          $ref: '#/components/schemas/MovieDescription'
        actors:
          type: array
          items:
            $ref: '#/components/schemas/ActorDTO'
        genres:
          type: array
          items:
            $ref: '#/components/schemas/GenreDTO'
        countries:
          type: array
          items:
            $ref: '#/components/schemas/CountryDTO'

    Sort:
      type: object
      title: Sort
      description: "Represents sorting information for ordering query results based on one or more criteria."
      properties:
        empty:
          type: boolean
          example: false
          description: |
            A boolean value indicating whether the sorting information is empty. 
            If `true`, there are no sorting criteria defined for the query.
        sorted:
          type: boolean
          example: true
          description: |
            A boolean value indicating whether the query results are sorted. 
            If `true`, the query includes sorting criteria.
        unsorted:
          type: boolean
          example: false
          description: |
            A boolean value indicating whether the query results are unsorted. 
            If `true`, the query results are not sorted according to any criteria.
            
    Pageable:
      type: object
      title: Pageable
      description: "Represents pagination and sorting information for querying a paginated dataset."
      properties:
        pageNumber:
          type: integer
          description: "The page number to retrieve."
          example: 0
        pageSize:
          type: integer
          description: "The maximum number of elements to be returned on each page."
          example: 2
        sort:
          $ref: '#/components/schemas/Sort'
        offset:
          type: integer
          format: int64
          description: "The offset of the current page within the result set."
          example: 0
        paged:
          type: boolean
          description: |
            A boolean value indicating whether the query results are paginated. 
            If `true`, the query includes pagination criteria.
          example: true
        unpaged:
          type: boolean
          description: |
            A boolean value indicating whether the query results are not paginated. 
            If `true`, the query results are not subject to pagination.
          example: false

    MoviePage:
      type: object
      description: "Represents a page of movies, including pagination and sorting information."
      properties:
        content:
          type: array
          description: "List of movies."
          items:
            $ref: '#/components/schemas/MovieResponse'
        pageable:
          $ref: '#/components/schemas/Pageable'
        last:
          type: boolean
          description: |
            A boolean value indicating whether this is the last page of data.
            If `true`, it is the last page; otherwise, it's not the last page.
          example: false
        totalElements:
          type: integer
          format: int64
          description: "The total number of items."
          example: 4
        totalPages:
          type: integer
          description: "The total number of pages needed to display all the data based on the page size."
          example: 2
        first:
          type: boolean
          description: |
            A boolean value indicating whether this is the first page of data.
            If `true`, it is the first page; otherwise, it's not the first page.
          example: true
        size:
          type: integer
          description: "The maximum number of items contained on each page."
          example: 2
        number:
          type: integer
          description: "The page number for the current page."
          example: 0
        sort:
          $ref: '#/components/schemas/Sort'
        numberOfElements:
          type: integer
          description: "The number of items on the current page."
          example: 2
        empty:
          type: boolean
          description: |
            A boolean value indicating whether the current page is empty.
            If `true`, the page has no items; otherwise, it has content.
          example: false

paths:
  /movies:
    post:
      description: Add movie to the database.
      summary: Add movie
      operationId: addMovie
      tags:
        - movies
      requestBody:
        description: A movie to be added to the database.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMovieRequest'
      responses:
        '201':
          description: Successfully added movie to the database.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResponse'
    get:
      description: Retrieves a list of the movies.
      summary: List movies
      operationId: getMovies
      tags:
        - movies
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/sort'
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/release'
        - $ref: '#/components/parameters/length'
        - $ref: '#/components/parameters/description'
        - $ref: '#/components/parameters/director'
        - $ref: '#/components/parameters/actors'
        - $ref: '#/components/parameters/genres'
        - $ref: '#/components/parameters/countries'
      responses:
        '200':
          description: Successfully retrieved a list of movies.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoviePage'

  /movies/{movieId}:
    get:
      description: Retrieve detailed information about a movie with a given ID.
      summary: Get movie details
      operationId: getMovie
      tags:
        - movies
      parameters:
        - $ref: '#/components/parameters/movieId'
      responses:
        '200':
          description: Successfully retrieved the movie details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResponse'
    put:
      description: Update details about a movie with a given ID.
      summary: Update movie details
      operationId: updateMovie
      tags:
        - movies
      parameters:
        - $ref: '#/components/parameters/movieId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMovieRequest'
      responses:
        '200':
          description: Successfully updated the movie details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResponse'
    delete:
      description: Delete a movie with a given ID.
      summary: Delete movie
      operationId: deleteMovie
      tags:
        - movies
      parameters:
        - $ref: '#/components/parameters/movieId'
      responses:
        '204':
          description: Successfully deleted the movie from the database.