# used for CORS and JWT claims retrieval
client:
  url: http://localhost:5173

# used for Auth0 authentication and authorization
okta:
  oauth2:
    audience: http://movie-hub-api
    issuer: https://dev-bzrzau6cj3i0m33i.us.auth0.com/

# used for healthcheck of the API in the docker-compose
management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-root.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# SpringDoc configuration for generating OpenAPI documentation
springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    url: openapi.yaml