services:
  db:
    image: postgres:16.4
    container_name: postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  keycloak:
    image: keycloak/keycloak:25.0.2
    container_name: keycloak
    ports:
      - "8090:8080"
    env_file:
      - .env
    networks:
      - spring-net
    command:
      - "start-dev"

  moviemanager:
    image: moviemanager
    container_name: moviemanager
    build:
      context: .
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    ports:
      - "8088:8080"
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  postgres_data: